{"pageProps":{"library":{"name":"RxJS","version":"6.6.0","description":"Reactive Extensions For JavaScript","groups":[{"name":"Creation","items":["of","from","fromPromise","interval","timer","defer","range","iif","constructor"]},{"name":"Filtering","items":["filter","find","first","auditTime","debounceTime","throttleTime","sampleTime","windowToggle"]},{"name":"Combination","items":["zip","forkJoin","race","combineLatest","withLatestFrom","startWith"]},{"name":"Error handling","items":["throwError","catch","retry","retryWhen","onErrorResumeNext"]},{"name":"Transformation","items":["map","pluck","buffer","mergeMap","switchMap","exhaustMap","concatMap","expand","toArray","windowWhen"]},{"name":"Multicasting","items":["share","shareReplay"]},{"name":"Utility","items":["tap","finalize","timeInterval","delay","delayWhen","dematerialize","repeat","timeout","pipe"]}]},"example":{"name":"onErrorResumeNext","title":"onErrorResumeNext","pageTitle":"RxJS onErrorResumeNext operator example + marble diagram","desc":"","docsUrl":"https://rxjs.dev/api/index/function/onErrorResumeNext","editUrl":"https://github.com/observable-playground/observable-playground/tree/master/src/examples/rxjs/files/onErrorResumeNext.md","content":"\n\n```js\nconst { rxObserver } = require('api/v0.3');\nconst { timer, onErrorResumeNext, throwError, of } = require('rxjs');\nconst { concat, ignoreElements } = require('rxjs/operators');\n\n\nconst failTimer$ = timer(5).pipe(\n    ignoreElements(),\n    concat(throwError('Ouch!'))\n  );\n\nconst fineTimer$ = timer(5).pipe(\n    ignoreElements(),\n    concat(of('Ok!'))\n  );\n\nconst strategicTimer$ = onErrorResumeNext(\n    failTimer$,\n    fineTimer$\n  );\n\nfailTimer$.subscribe(rxObserver('fail timer'));\nfineTimer$.subscribe(rxObserver('fine timer'));\nstrategicTimer$.subscribe(rxObserver('strategic'));\n\n```\n\nCheck out [\"Error handling in RxJS\"](https://medium.com/@kddsky/error-handling-in-rxjs-bac0f96a7def) article to get better understanding how not to fail with Observables."}},"__N_SSG":true}